CRYPTO_CONFIG_ROOT_FOLDER="$PWD/client"
ORG_NAME=excise
Identity=admin
 
export CORE_PEER_MSPCONFIGPATH=$CRYPTO_CONFIG_ROOT_FOLDER/$ORG_NAME/$Identity/msp
export FABRIC_CFG_PATH="$CRYPTO_CONFIG_ROOT_FOLDER/$ORG_NAME"
 
